"""Generate a PyInstaller --version-file from ual_timeliner.__version__.

Run as: python _make_version_info.py [output_path]
Default output_path: version_info.txt next to this script.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def _read_version(script: Path) -> str:
    text = script.read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not match:
        raise SystemExit(f"Could not find __version__ in {script}")
    return match.group(1)


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    # Strip pre-release/build metadata: "1.2.3-rc1+meta" -> "1.2.3"
    core = re.split(r"[-+]", version, maxsplit=1)[0]
    parts = [int(p) for p in core.split(".") if p.isdigit()]
    parts = (parts + [0, 0, 0, 0])[:4]
    return tuple(parts)  # type: ignore[return-value]


TEMPLATE = """# UTF-8
# Auto-generated by _make_version_info.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vers},
    prodvers={vers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'BriMor Labs / Kevin Stokes'),
         StringStruct('FileDescription', 'UAL Timeline Generator'),
         StringStruct('FileVersion', '{vstr}'),
         StringStruct('InternalName', 'ual-timeliner'),
         StringStruct('OriginalFilename', 'ual-timeliner.exe'),
         StringStruct('ProductName', 'ual-timeliner'),
         StringStruct('ProductVersion', '{vstr}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main(argv: list[str]) -> int:
    here = Path(__file__).resolve().parent
    script = here / "ual_timeliner.py"
    output = Path(argv[1]) if len(argv) > 1 else here / "version_info.txt"

    version = _read_version(script)
    vers = _version_tuple(version)
    output.write_text(TEMPLATE.format(vers=vers, vstr=version), encoding="utf-8")
    print(f"Wrote {output} (version {version} -> {vers})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
